package steps

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strconv"
	"text/template"

	instconfig "github.com/Josepavese/aftertalk/cmd/installer/config"
)

func stepConfigWrite() *Step {
	return &Step{
		ID:          "30-config",
		Description: "Write aftertalk.yaml configuration file",
		Run:         runConfigWrite,
	}
}

const yamlTemplate = `# Generated by aftertalk-installer — do not edit manually.
# To reconfigure, run: aftertalk-installer --configure

http:
  port: {{ .HTTPPort }}
  host: "0.0.0.0"

database:
  path: "{{ .ServiceRoot }}/aftertalk.db"

api:
  key: "{{ .APIKey }}"

jwt:
  secret:     "{{ .JWTSecret }}"
  issuer:     "{{ .JWTIssuer }}"
  expiration: "{{ .JWTExpiry }}"

stt:
  provider: "{{ .STTProvider }}"

llm:
  provider: "{{ .LLMProvider }}"
{{ range $k,$v := .LLMConfig }}{{ if eq $k "LLM_API_KEY" }}  openai:
    api_key: "{{ $v }}"
{{ end }}{{ end }}
webhook:
  url:           "{{ .WebhookURL }}"
  mode:          "{{ .WebhookMode }}"
  secret:        "{{ .WebhookSecret }}"
  pull_base_url: "{{ .WebhookPullBase }}"
  token_ttl:     "{{ .WebhookTokenTTL }}"
  max_retries:   {{ .WebhookMaxRetries }}

session:
  max_duration:       "{{ .SessionMaxDuration }}"
  inactivity_timeout: "{{ .SessionInactivityTimeout }}"

logging:
  level: info
  format: json
`

const yamlTLSAppend = `
tls:
  cert_file: "{{ .TLSCertFile }}"
  key_file:  "{{ .TLSKeyFile }}"
`

func runConfigWrite(_ context.Context, cfg *instconfig.InstallConfig, log Logger) error {
	cfgPath := filepath.Join(cfg.ServiceRoot, "aftertalk.yaml")

	// Render main template
	t, err := template.New("yaml").Parse(yamlTemplate)
	if err != nil {
		return fmt.Errorf("parse yaml template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, cfg); err != nil {
		return fmt.Errorf("render yaml: %w", err)
	}

	// Append TLS section if configured
	if cfg.TLSCertFile != "" && cfg.TLSKeyFile != "" {
		tTLS, err := template.New("tls").Parse(yamlTLSAppend)
		if err != nil {
			return fmt.Errorf("parse tls template: %w", err)
		}
		if err := tTLS.Execute(&buf, cfg); err != nil {
			return fmt.Errorf("render tls section: %w", err)
		}
		log.Info(fmt.Sprintf("TLS configured: cert=%s", cfg.TLSCertFile))
	}

	if err := os.WriteFile(cfgPath, buf.Bytes(), 0o640); err != nil { //nolint:gosec
		return fmt.Errorf("write %s: %w", cfgPath, err)
	}
	log.Info("written: " + cfgPath)

	// Write provider-specific env vars to /etc/aftertalk/aftertalk.env
	// (read by the systemd unit via EnvironmentFile=)
	envPath := "/etc/aftertalk/aftertalk.env"
	if err := os.MkdirAll(filepath.Dir(envPath), 0o755); err == nil {
		var envBuf bytes.Buffer
		for k, v := range cfg.STTConfig {
			fmt.Fprintf(&envBuf, "%s=%s\n", k, v)
		}
		for k, v := range cfg.LLMConfig {
			fmt.Fprintf(&envBuf, "%s=%s\n", k, v)
		}
		if err := os.WriteFile(envPath, envBuf.Bytes(), 0o640); err != nil { //nolint:gosec
			log.Warn(fmt.Sprintf("could not write %s: %v", envPath, err))
		} else {
			log.Info("written: " + envPath)
		}
	}

	// Chown config files to service user so the process can read them.
	// Without this, files written by root are inaccessible to the service user.
	if u, err := user.Lookup(cfg.ServiceUser); err == nil {
		uid, _ := strconv.Atoi(u.Uid)
		gid, _ := strconv.Atoi(u.Gid)
		for _, p := range []string{cfgPath, envPath} {
			if chownErr := os.Chown(p, uid, gid); chownErr != nil {
				log.Warn(fmt.Sprintf("chown %s: %v", p, chownErr))
			}
		}
		log.Info(fmt.Sprintf("chown %s: %s", cfg.ServiceUser, cfgPath))
	}

	return nil
}
