package steps

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	instconfig "github.com/Josepavese/aftertalk/cmd/installer/config"
)

func stepConfigWrite() *Step {
	return &Step{
		ID:          "30-config",
		Description: "Write aftertalk.yaml configuration file",
		Run:         runConfigWrite,
	}
}

const yamlTemplate = `# Generated by aftertalk-installer — do not edit manually.
# To reconfigure, run: aftertalk-installer --configure

http:
  port: {{ .HTTPPort }}
  host: "0.0.0.0"

database:
  path: "{{ .ServiceRoot }}/aftertalk.db"

api:
  key: "{{ .APIKey }}"

jwt:
  secret:     "{{ .JWTSecret }}"
  issuer:     "{{ .JWTIssuer }}"
  expiration: "{{ .JWTExpiry }}"

stt:
  provider: "{{ .STTProvider }}"
{{ if .STTDefaultProfile }}  default_profile: "{{ .STTDefaultProfile }}"
{{ end }}{{ if usesSTTProvider . "whisper-local" }}  whisper_local:
    url:      "{{ .WhisperURL }}"
    model:    "{{ .WhisperModel }}"
    language: "{{ .WhisperLanguage }}"
{{ end }}{{ if usesSTTProvider . "google" }}  google:
    credentials_path: "{{ index .STTConfig "GOOGLE_APPLICATION_CREDENTIALS" }}"
{{ end }}{{ if usesSTTProvider . "aws" }}  aws:
    access_key_id:     "{{ index .STTConfig "AWS_ACCESS_KEY_ID" }}"
    secret_access_key: "{{ index .STTConfig "AWS_SECRET_ACCESS_KEY" }}"
    region:            "{{ index .STTConfig "AWS_REGION" }}"
{{ end }}{{ if usesSTTProvider . "azure" }}  azure:
    key:    "{{ index .STTConfig "AZURE_SPEECH_KEY" }}"
    region: "{{ index .STTConfig "AZURE_SPEECH_REGION" }}"
{{ end }}{{ if .STTProfiles }}  profiles:
{{ range $name, $p := .STTProfiles }}    {{ $name }}:
      provider: "{{ $p.Provider }}"
{{ if $p.Model }}      model: "{{ $p.Model }}"
{{ end }}{{ if $p.URL }}      url: "{{ $p.URL }}"
{{ end }}{{ if $p.APIKey }}      api_key: "{{ $p.APIKey }}"
{{ end }}{{ end }}{{ end }}
llm:
  provider: "{{ .LLMProvider }}"
{{ if .LLMDefaultProfile }}  default_profile: "{{ .LLMDefaultProfile }}"
{{ end }}{{ if usesLLMProvider . "ollama" }}  ollama:
    base_url: "{{ .OllamaURL }}"
    model:    "{{ .OllamaModel }}"
{{ if index .LLMConfig "OLLAMA_THINK" }}    think: {{ index .LLMConfig "OLLAMA_THINK" }}
{{ end }}{{ end }}{{ if usesLLMProvider . "openai" }}  openai:
    api_key: "{{ cfgValue .LLMConfig "LLM_API_KEY" "OPENAI_API_KEY" }}"
{{ if index .LLMConfig "LLM_MODEL" }}    model:   "{{ index .LLMConfig "LLM_MODEL" }}"
{{ end }}{{ if index .LLMConfig "LLM_BASE_URL" }}    base_url: "{{ index .LLMConfig "LLM_BASE_URL" }}"
{{ end }}{{ if index .LLMConfig "LLM_REQUEST_TIMEOUT" }}    request_timeout: "{{ index .LLMConfig "LLM_REQUEST_TIMEOUT" }}"
{{ end }}{{ if index .LLMConfig "LLM_MAX_TOKENS" }}    max_tokens: {{ index .LLMConfig "LLM_MAX_TOKENS" }}
{{ end }}{{ if hasReasoning .LLMConfig }}    reasoning:
{{ if index .LLMConfig "LLM_REASONING_ENABLED" }}      enabled: {{ index .LLMConfig "LLM_REASONING_ENABLED" }}
{{ end }}{{ if index .LLMConfig "LLM_REASONING_EFFORT" }}      effort: "{{ index .LLMConfig "LLM_REASONING_EFFORT" }}"
{{ end }}{{ if index .LLMConfig "LLM_REASONING_EXCLUDE" }}      exclude: {{ index .LLMConfig "LLM_REASONING_EXCLUDE" }}
{{ end }}{{ end }}{{ end }}{{ if usesLLMProvider . "anthropic" }}  anthropic:
    api_key: "{{ cfgValue .LLMConfig "LLM_API_KEY" "ANTHROPIC_API_KEY" }}"
    model:   "{{ index .LLMConfig "LLM_MODEL" }}"
{{ if index .LLMConfig "LLM_REQUEST_TIMEOUT" }}    request_timeout: "{{ index .LLMConfig "LLM_REQUEST_TIMEOUT" }}"
{{ end }}{{ if index .LLMConfig "LLM_MAX_TOKENS" }}    max_tokens: {{ index .LLMConfig "LLM_MAX_TOKENS" }}
{{ end }}{{ end }}{{ if usesLLMProvider . "azure" }}  azure:
    api_key:  "{{ cfgValue .LLMConfig "LLM_API_KEY" "AZURE_OPENAI_API_KEY" }}"
    endpoint: "{{ index .LLMConfig "AZURE_OPENAI_ENDPOINT" }}"
    model:    "{{ index .LLMConfig "LLM_MODEL" }}"
{{ if index .LLMConfig "LLM_REQUEST_TIMEOUT" }}    request_timeout: "{{ index .LLMConfig "LLM_REQUEST_TIMEOUT" }}"
{{ end }}{{ if index .LLMConfig "LLM_MAX_TOKENS" }}    max_tokens: {{ index .LLMConfig "LLM_MAX_TOKENS" }}
{{ end }}{{ if hasReasoning .LLMConfig }}    reasoning:
{{ if index .LLMConfig "LLM_REASONING_ENABLED" }}      enabled: {{ index .LLMConfig "LLM_REASONING_ENABLED" }}
{{ end }}{{ if index .LLMConfig "LLM_REASONING_EFFORT" }}      effort: "{{ index .LLMConfig "LLM_REASONING_EFFORT" }}"
{{ end }}{{ if index .LLMConfig "LLM_REASONING_EXCLUDE" }}      exclude: {{ index .LLMConfig "LLM_REASONING_EXCLUDE" }}
{{ end }}{{ end }}
{{ end }}{{ if .LLMProfiles }}  profiles:
{{ range $name, $p := .LLMProfiles }}    {{ $name }}:
      provider: "{{ $p.Provider }}"
{{ if $p.Model }}      model: "{{ $p.Model }}"
{{ end }}{{ if $p.APIKey }}      api_key: "{{ $p.APIKey }}"
{{ end }}{{ if $p.BaseURL }}      base_url: "{{ $p.BaseURL }}"
{{ end }}{{ if $p.Endpoint }}      endpoint: "{{ $p.Endpoint }}"
{{ end }}{{ if $p.Deployment }}      deployment: "{{ $p.Deployment }}"
{{ end }}{{ if $p.RequestTimeout }}      request_timeout: "{{ $p.RequestTimeout }}"
{{ end }}{{ if $p.MaxTokens }}      max_tokens: {{ $p.MaxTokens }}
{{ end }}{{ if $p.Think }}      think: {{ boolPtr $p.Think }}
{{ end }}{{ if profileReasoning $p }}      reasoning:
{{ if $p.Reasoning.Enabled }}        enabled: {{ boolPtr $p.Reasoning.Enabled }}
{{ end }}{{ if $p.Reasoning.Effort }}        effort: "{{ $p.Reasoning.Effort }}"
{{ end }}{{ if $p.Reasoning.Exclude }}        exclude: true
{{ end }}{{ end }}{{ end }}{{ end }}
webhook:
  url:           "{{ .WebhookURL }}"
  mode:          "{{ .WebhookMode }}"
  secret:        "{{ .WebhookSecret }}"
  pull_base_url: "{{ .WebhookPullBase }}"
  token_ttl:     "{{ .WebhookTokenTTL }}"
  max_retries:   {{ .WebhookMaxRetries }}

session:
  max_duration:       "{{ .SessionMaxDuration }}"
  inactivity_timeout: "{{ .SessionInactivityTimeout }}"

logging:
  level: info
  format: json

webrtc:
  ice_udp_port_min: {{ .ICEUDPPortMin }}
  ice_udp_port_max: {{ .ICEUDPPortMax }}
{{ if .TURNEnabled }}  turn:
    enabled: true
    listen_addr: "{{ .TURNListenAddr }}"
    public_ip:   "{{ .TURNPublicIP }}"
    realm:       "{{ .TURNRealm }}"
    auth_secret: "{{ .TURNAuthSecret }}"
    auth_ttl:    {{ .TURNAuthTTL }}
    enable_udp:  {{ .TURNEnableUDP }}
    enable_tcp:  {{ .TURNEnableTCP }}
{{ end }}`

const yamlTLSAppend = `
tls:
  cert_file: "{{ .TLSCertFile }}"
  key_file:  "{{ .TLSKeyFile }}"
`

func runConfigWrite(_ context.Context, cfg *instconfig.InstallConfig, log Logger) error {
	cfgPath := filepath.Join(cfg.ServiceRoot, "aftertalk.yaml")

	// Render main template
	t, err := template.New("yaml").Funcs(template.FuncMap{
		"usesSTTProvider":  usesSTTProvider,
		"usesLLMProvider":  usesLLMProvider,
		"cfgValue":         cfgValue,
		"hasReasoning":     hasReasoning,
		"profileReasoning": profileReasoning,
		"boolPtr":          boolPtr,
	}).Parse(yamlTemplate)
	if err != nil {
		return fmt.Errorf("parse yaml template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, cfg); err != nil {
		return fmt.Errorf("render yaml: %w", err)
	}

	// Append TLS section if configured
	if cfg.TLSCertFile != "" && cfg.TLSKeyFile != "" {
		tTLS, err := template.New("tls").Parse(yamlTLSAppend)
		if err != nil {
			return fmt.Errorf("parse tls template: %w", err)
		}
		if err := tTLS.Execute(&buf, cfg); err != nil {
			return fmt.Errorf("render tls section: %w", err)
		}
		log.Info(fmt.Sprintf("TLS configured: cert=%s", cfg.TLSCertFile))
	}

	if err := os.WriteFile(cfgPath, buf.Bytes(), 0o640); err != nil { //nolint:gosec
		return fmt.Errorf("write %s: %w", cfgPath, err)
	}
	log.Info("written: " + cfgPath)

	// Write provider-specific env vars to /etc/aftertalk/aftertalk.env
	// (read by the systemd unit via EnvironmentFile=)
	envPath := "/etc/aftertalk/aftertalk.env"
	if err := os.MkdirAll(filepath.Dir(envPath), 0o755); err == nil {
		var envBuf bytes.Buffer
		for k, v := range cfg.STTConfig {
			fmt.Fprintf(&envBuf, "%s=%s\n", k, v)
		}
		for k, v := range cfg.LLMConfig {
			fmt.Fprintf(&envBuf, "%s=%s\n", k, v)
		}
		if err := os.WriteFile(envPath, envBuf.Bytes(), 0o640); err != nil { //nolint:gosec
			log.Warn(fmt.Sprintf("could not write %s: %v", envPath, err))
		} else {
			log.Info("written: " + envPath)
		}
	}

	// Chown config files to service user so the process can read them.
	// Without this, files written by root are inaccessible to the service user.
	if u, err := user.Lookup(cfg.ServiceUser); err == nil {
		uid, _ := strconv.Atoi(u.Uid)
		gid, _ := strconv.Atoi(u.Gid)
		for _, p := range []string{cfgPath, envPath} {
			if chownErr := os.Chown(p, uid, gid); chownErr != nil {
				log.Warn(fmt.Sprintf("chown %s: %v", p, chownErr))
			}
		}
		log.Info(fmt.Sprintf("chown %s: %s", cfg.ServiceUser, cfgPath))
	}

	return nil
}

func usesSTTProvider(cfg *instconfig.InstallConfig, provider string) bool {
	if cfg.STTProvider == provider {
		return true
	}
	for _, profile := range cfg.STTProfiles {
		if profile.Provider == provider {
			return true
		}
	}
	return false
}

func usesLLMProvider(cfg *instconfig.InstallConfig, provider string) bool {
	if cfg.LLMProvider == provider {
		return true
	}
	for _, profile := range cfg.LLMProfiles {
		if profile.Provider == provider {
			return true
		}
	}
	return false
}

func cfgValue(values map[string]string, keys ...string) string {
	for _, key := range keys {
		if v := strings.TrimSpace(values[key]); v != "" {
			return v
		}
	}
	return ""
}

func hasReasoning(values map[string]string) bool {
	return cfgValue(values, "LLM_REASONING_ENABLED", "LLM_REASONING_EFFORT", "LLM_REASONING_EXCLUDE") != ""
}

func profileReasoning(profile instconfig.LLMProfileEntry) bool {
	return profile.Reasoning.Enabled != nil || profile.Reasoning.Effort != "" || profile.Reasoning.Exclude
}

func boolPtr(v *bool) bool {
	return v != nil && *v
}
