package llm

import (
	"fmt"
	"strings"

	"github.com/flowup/aftertalk/internal/config"
)

// GenerateMinutesPrompt builds a dynamic LLM prompt from the given template.
// The JSON schema in the prompt mirrors the template sections so the same
// prompt builder works for any domain (therapy, consulting, legal, etc.).
func GenerateMinutesPrompt(transcriptionText string, tmpl config.TemplateConfig) string {
	rolesDesc := formatRoles(tmpl.Roles)
	schemaExample := buildSchemaExample(tmpl)
	sectionRules := buildSectionRules(tmpl)

	return fmt.Sprintf(`You are a professional session secretary. Analyze the transcript below and produce structured meeting minutes.

⚠️ LANGUAGE RULE — HIGHEST PRIORITY: Detect the language of the TRANSCRIPT and write ALL output text IN THAT SAME LANGUAGE. NEVER translate or switch to English.

IMPORTANT — STT ERRORS: The transcript was generated by automatic speech recognition and may contain errors or nonsense words. Correct obvious errors using context, but NEVER invent content not inferable from the transcript.

SESSION TEMPLATE: %s
PARTICIPANT ROLES: %s

TRANSCRIPT:
%s

Produce a JSON object with this exact structure:
%s

RULES:
- Base everything strictly on the transcript; do not fabricate.
- Correct obvious STT errors using context but do not invent new meaning.
- If the transcript is empty or unintelligible, return all empty arrays/objects.
- "timestamp" and "timestamp_ms" must be the exact integer from the [Xms role] prefix of the source line.
- ALL text fields MUST be in the same language as the transcript — no exceptions.
%s- Do NOT include diagnoses or clinical assessments.
- Respond ONLY with valid JSON — no extra text, no markdown fences.`,
		tmpl.Name,
		rolesDesc,
		transcriptionText,
		schemaExample,
		sectionRules,
	)
}

// buildSchemaExample generates the JSON schema comment block shown to the LLM.
func buildSchemaExample(tmpl config.TemplateConfig) string {
	var sb strings.Builder
	sb.WriteString("{\n")
	sb.WriteString("  \"sections\": {\n")

	for i, sec := range tmpl.Sections {
		comma := ","
		if i == len(tmpl.Sections)-1 {
			comma = ""
		}
		switch sec.Type {
		case "string_list":
			sb.WriteString(fmt.Sprintf("    %q: [\"item 1\", \"item 2\"]%s\n", sec.Key, comma))
		case "content_items":
			sb.WriteString(fmt.Sprintf("    %q: [{\"text\": \"synthesized point\", \"timestamp\": 0}]%s\n", sec.Key, comma))
		case "progress":
			sb.WriteString(fmt.Sprintf("    %q: {\"progress\": [\"progress item\"], \"issues\": [\"issue\"]}%s\n", sec.Key, comma))
		default:
			sb.WriteString(fmt.Sprintf("    %q: []%s\n", sec.Key, comma))
		}
	}

	sb.WriteString("  },\n")
	sb.WriteString("  \"citations\": [\n")
	sb.WriteString("    {\"timestamp_ms\": 0, \"text\": \"verbatim quote from transcript\", \"role\": \"role_key\"}\n")
	sb.WriteString("  ]\n")
	sb.WriteString("}")
	return sb.String()
}

// buildSectionRules generates per-section instructions for the LLM.
func buildSectionRules(tmpl config.TemplateConfig) string {
	var sb strings.Builder
	for _, sec := range tmpl.Sections {
		sb.WriteString(fmt.Sprintf("- sections.%s: %s\n", sec.Key, sec.Description))
	}
	sb.WriteString(fmt.Sprintf("- citations.role must be one of: %s\n", formatRoleKeys(tmpl.Roles)))
	return sb.String()
}

func formatRoles(roles []config.RoleConfig) string {
	if len(roles) == 0 {
		return "unknown"
	}
	parts := make([]string, len(roles))
	for i, r := range roles {
		parts[i] = fmt.Sprintf("%s (%s)", r.Label, r.Key)
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return strings.Join(parts[:len(parts)-1], ", ") + " and " + parts[len(parts)-1]
}

func formatRoleKeys(roles []config.RoleConfig) string {
	keys := make([]string, len(roles))
	for i, r := range roles {
		keys[i] = r.Key
	}
	return strings.Join(keys, ", ")
}
