package webrtc

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha1" //nolint:gosec // TURN RFC 5766 mandates HMAC-SHA1
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net"
	"strings"
	"time"

	"github.com/pion/turn/v4"

	"github.com/Josepavese/aftertalk/internal/config"
	"github.com/Josepavese/aftertalk/internal/logging"
)

var (
	errTURNBothDisabled   = errors.New("turn: both UDP and TCP are disabled — enable at least one")
	errUnexpectedAddrType = errors.New("unexpected local addr type")
)

// TURNServer wraps a pion/turn server with lifecycle management.
// Start it with StartTURNServer and stop it by canceling the context.
type TURNServer struct {
	server *turn.Server
	addr   string // host:port actually bound (may differ from ListenAddr)
	secret string // HMAC-SHA1 shared secret for credential generation
}

// Addr returns the host:port the TURN server is listening on.
func (s *TURNServer) Addr() string { return s.addr }

// GenerateCredentials returns a time-limited TURN username/credential pair
// valid for ttl seconds, using the HMAC-SHA1 REST API mechanism (RFC 5766 §6).
//
// username format: "<expiry_unix>:<label>"
// credential:      base64(HMAC-SHA1(secret, username))
func (s *TURNServer) GenerateCredentials(label string, ttl int) (username, credential string) {
	if ttl <= 0 {
		ttl = 86400
	}
	expiry := time.Now().Add(time.Duration(ttl) * time.Second).Unix()
	username = fmt.Sprintf("%d:%s", expiry, label)
	mac := hmac.New(sha1.New, []byte(s.secret)) //nolint:gosec
	mac.Write([]byte(username))
	credential = base64.StdEncoding.EncodeToString(mac.Sum(nil))
	return username, credential
}

// StartTURNServer starts a pion/turn server according to cfg.
// It listens on both UDP and TCP when enabled. The server shuts down
// gracefully when ctx is canceled.
func StartTURNServer(ctx context.Context, cfg config.TURNServerConfig) (*TURNServer, error) {
	secret := cfg.AuthSecret
	if secret == "" {
		secret = randomSecret(32)
		logging.Warnf("TURN: no auth_secret configured, using ephemeral secret (will change on restart)")
	}

	publicIP := cfg.PublicIP
	if publicIP == "" {
		var err error
		publicIP, err = detectPublicIP() //nolint:contextcheck // detectPublicIP creates its own context with timeout
		if err != nil {
			logging.Warnf("TURN: could not auto-detect public IP (%v); TURN may not work over WAN", err)
			publicIP = "127.0.0.1"
		} else {
			logging.Infof("TURN: auto-detected public IP: %s", publicIP)
		}
	}

	_, portStr, err := net.SplitHostPort(cfg.ListenAddr)
	if err != nil {
		return nil, fmt.Errorf("turn: invalid listen_addr %q: %w", cfg.ListenAddr, err)
	}

	realm := cfg.Realm
	if realm == "" {
		realm = "aftertalk"
	}

	// Build the list of PacketConnConfigs (UDP) and ListenerConfigs (TCP).
	var packetConns []turn.PacketConnConfig
	var listeners []turn.ListenerConfig

	if cfg.EnableUDP {
		udpAddr, udpErr := net.ResolveUDPAddr("udp4", cfg.ListenAddr)
		if udpErr != nil {
			return nil, fmt.Errorf("turn: resolve UDP addr: %w", udpErr)
		}
		udpConn, udpErr := net.ListenUDP("udp4", udpAddr)
		if udpErr != nil {
			return nil, fmt.Errorf("turn: listen UDP %s: %w", cfg.ListenAddr, udpErr)
		}
		packetConns = append(packetConns, turn.PacketConnConfig{
			PacketConn:            udpConn,
			RelayAddressGenerator: relayGenerator(publicIP),
		})
		logging.Infof("TURN: UDP listening on %s (public: %s:%s)", cfg.ListenAddr, publicIP, portStr)
	}

	if cfg.EnableTCP {
		tcpAddr, tcpErr := net.ResolveTCPAddr("tcp4", cfg.ListenAddr)
		if tcpErr != nil {
			return nil, fmt.Errorf("turn: resolve TCP addr: %w", tcpErr)
		}
		tcpListener, tcpErr := net.ListenTCP("tcp4", tcpAddr)
		if tcpErr != nil {
			return nil, fmt.Errorf("turn: listen TCP %s: %w", cfg.ListenAddr, tcpErr)
		}
		listeners = append(listeners, turn.ListenerConfig{
			Listener:              tcpListener,
			RelayAddressGenerator: relayGenerator(publicIP),
		})
		logging.Infof("TURN: TCP listening on %s (public: %s:%s)", cfg.ListenAddr, publicIP, portStr)
	}

	if len(packetConns) == 0 && len(listeners) == 0 {
		return nil, errTURNBothDisabled
	}

	srv, err := turn.NewServer(turn.ServerConfig{
		Realm:             realm,
		AuthHandler:       hmacAuthHandler(secret),
		PacketConnConfigs: packetConns,
		ListenerConfigs:   listeners,
	})
	if err != nil {
		return nil, fmt.Errorf("turn: create server: %w", err)
	}

	ts := &TURNServer{
		server: srv,
		addr:   fmt.Sprintf("%s:%s", publicIP, portStr),
		secret: secret,
	}

	// Shutdown when context is canceled.
	go func() {
		<-ctx.Done()
		logging.Infof("TURN: shutting down")
		if err := srv.Close(); err != nil {
			logging.Warnf("TURN: shutdown error: %v", err)
		}
	}()

	return ts, nil
}

// hmacAuthHandler returns a pion/turn AuthHandler that validates credentials
// generated by GenerateCredentials (HMAC-SHA1 REST API, RFC 5766 §6).
func hmacAuthHandler(secret string) turn.AuthHandler {
	return func(username, realm string, srcAddr net.Addr) ([]byte, bool) {
		// username format: "<expiry_unix>:<label>"
		parts := strings.SplitN(username, ":", 2)
		if len(parts) != 2 {
			return nil, false
		}
		// The password is: base64(HMAC-SHA1(secret, username))
		mac := hmac.New(sha1.New, []byte(secret)) //nolint:gosec
		mac.Write([]byte(username))
		password := mac.Sum(nil)
		// pion/turn expects the raw password bytes (not base64).
		return password, true
	}
}

// relayGenerator returns a RelayAddressGenerator that binds relay ports on publicIP.
func relayGenerator(publicIP string) turn.RelayAddressGenerator {
	return &turn.RelayAddressGeneratorStatic{
		RelayAddress: net.ParseIP(publicIP),
		Address:      "0.0.0.0",
	}
}

// detectPublicIP fetches the machine's public IPv4 via api.ipify.org.
func detectPublicIP() (string, error) {
	// Use a simple UDP dial to a well-known address to get the local outbound IP
	// (avoids HTTP dependency for simple LAN scenarios).
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	dialer := &net.Dialer{}
	conn, err := dialer.DialContext(ctx, "udp4", "8.8.8.8:53")
	if err != nil {
		return "", err
	}
	defer conn.Close() //nolint:errcheck // best-effort close of UDP conn
	localAddr, ok := conn.LocalAddr().(*net.UDPAddr)
	if !ok {
		return "", errUnexpectedAddrType
	}
	return localAddr.IP.String(), nil
}

// randomSecret returns a URL-safe base64 random string of n bytes.
func randomSecret(n int) string {
	b := make([]byte, n)
	if _, err := io.ReadFull(rand.Reader, b); err != nil {
		panic("turn: crypto/rand failed: " + err.Error())
	}
	return base64.RawURLEncoding.EncodeToString(b)
}
